# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ESalesmanHelpCenterDeployment

on:
  push:
    branches:
      - main
  label:
    types: [created, deleted]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # First SSH is do something before copy and Last SSH is do something after copy
      - name: Copy with SCP To Remote Host
        uses: cross-the-world/scp-pipeline@v1.1.0
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USERNAME}}
          pass: ${{secrets.PASSWORD}}
          port: 22
          connect_timeout: 60s
          local: './build/*'
          remote: /home/worker/helpcenter/

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          port: 22
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |-
            cd /home/worker/
            cp -r helpcenter /var/www/html/
            echo "Success"
